### ISSUE TITLE
Please tag 0.1.2

### ISSUE THREAD

**Issue by matthiasbeyer** [aumayr/beancount-pygments-lexer#1]
What the title says.

**Comment by aumayr** [comment]
@matthiasbeyer We do not use pygments in Fava anymore (we switched to CodeMirror). 

As you seem to have interest in this project: Do you want to take over the ownership of the beancount-pygments-lexer-code and repo?

**Comment by matthiasbeyer** [comment]
@aumayr Hm... but version 0.3.0 of fava depends on this,... 

---

I'm not a python guy, sorry. I packaged a lot of python software in nixpkgs, but I never wrote a single line of python myself, so ... I guess there are others that are better qualified, sorry!

**Comment by aumayr** [comment]
No problem - I will tag 0.1.2, and it will remain online of course, as the soon-to-be-old version of fava (0.3.0) depends on it.

**Comment by aumayr** [comment]
https://github.com/aumayr/beancount-pygments-lexer/releases/tag/v0.1.2
